_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 1
  BACKBONE:
    FREEZE: True
DATASETS:
  TRAIN: ('custom_rod_base',)
  TEST: ('custom_rod_base',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (14400,)
  MAX_ITER: 16000
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 30
OUTPUT_DIR: "/content/gdrive/MyDrive/fsdet-v/Custom-Rod/rod-only-foreground"