_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./model_reset_combine.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 4
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
# Implicitně se tady zatím bude brát, že ..._all trénuje s 10-shot
  TRAIN: ('custom_bear_all',)
  TEST: ('custom_bear_all',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (14400,)
  MAX_ITER: 16000
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 10
OUTPUT_DIR: "/content/gdrive/MyDrive/fsdet-v"
